<a href="https://colab.research.google.com/github/benasphy/Deep-Learning/blob/main/Weight_Initializations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- **Xavier Initialization**

In [5]:
import numpy as np

n_in, n_out = 4, 3

# Xavier uniform
limit = np.sqrt(6 / (n_in + n_out))
W_xavier = np.random.uniform(-limit, limit, (n_out, n_in))

print("Limit:", limit)
print("Xavier Initialized Weights:\n", W_xavier)
print("Variance:", np.var(W_xavier))


Limit: 0.9258200997725514
Xavier Initialized Weights:
 [[-0.58003584  0.36070579  0.2724197   0.41277228]
 [-0.11463076 -0.32060039 -0.29779016 -0.41057954]
 [-0.01415254 -0.39867685 -0.45882627 -0.41464514]]
Variance: 0.10870536480379438


- **HE Initialization**

In [6]:
import numpy as np

n_in, n_out = 4, 3

# He normal initialization
std = np.sqrt(2 / n_in)
W_he = np.random.randn(n_out, n_in) * std

print("Standard deviation:", std)
print("He Initialized Weights:\n", W_he)
print("Variance:", np.var(W_he))


Standard deviation: 0.7071067811865476
He Initialized Weights:
 [[ 0.4414543  -0.21806477  0.10625153  0.17166327]
 [ 0.32359117  0.10024445  0.31064536  1.16559534]
 [ 0.35565617  0.72480002  0.54745672  0.13630596]]
Variance: 0.11476344310933373
